[package]
name = "ruxc"
version = "2.0.0"
authors = ["Daniel-Constantin Mierla <miconda@gmail.com>"]
edition = "2021"
rust-version = "1.88"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.190"
ureq = { version = "3.4.2", default-features = false, features = ["rustls"] }
url = "2.5.8"

[lib]
name = "ruxc"
path = "src/ruxc.rs"
crate-type = ["staticlib", "cdylib"]
